package com.yingge.qa.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
public class ProblemSubclassDTO implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     */
    private Long id;

    /**
     */
    private Date gmtCreate;

    /**
     */
    private Date gmtModified;

    /**
     *   分类名称
     */
    private String classificationName;

    /**
     *   子类名称
     */
    private String subclassName;

    /**
     *   父类id
     */
    private Long respondent;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Date getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getClassificationName() {
        return classificationName;
    }

    public void setClassificationName(String classificationName) {
        this.classificationName = classificationName;
    }

    public String getSubclassName() {
        return subclassName;
    }

    public void setSubclassName(String subclassName) {
        this.subclassName = subclassName;
    }

    public Long getRespondent() {
        return respondent;
    }

    public void setRespondent(Long respondent) {
        this.respondent = respondent;
    }
}