package com.yingge.qa.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
public class UserRoleRefDTO implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     *   编号
     */
    private Long id;

    /**
     *   创建时间
     */
    private Date gmtCreate;

    /**
     *   修改时间
     */
    private Date gmtModified;

    /**
     *   是否删除 1 删除 0未删除
     */
    private Byte isDelete;

    /**
     *   创建人
     */
    private Long creatorId;

    /**
     *   修改人
     */
    private Long modifierId;

    /**
     *   用户id
     */
    private Long userId;

    /**
     *   角色id
     */
    private Long roleId;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Date getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public Byte getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    public Long getCreatorId() {
        return creatorId;
    }

    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    public Long getModifierId() {
        return modifierId;
    }

    public void setModifierId(Long modifierId) {
        this.modifierId = modifierId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getRoleId() {
        return roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}