package com.yingge.qa.dao;

import com.yingge.qa.entity.AnswerDO;
import com.yingge.qa.entity.AnswerParam;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
@Mapper
public interface AnswerDAO {
    /**
     * 根据WHERE条件COUNT
     * @param answerParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(AnswerParam answerParam);

    /**
     * 根据WHERE条件删除
     * @param answerParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(AnswerParam answerParam);

    /**
     * 根据主键删除
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * 插件单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(AnswerDO record);

    /**
     * 根据字段选择性插件单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(AnswerDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param answerParam
     * @return
     *
     * @mbg.generated
     */
    List<AnswerDO> selectByParam(AnswerParam answerParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    AnswerDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param answerParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") AnswerDO record, @Param("answerParam") AnswerParam answerParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param answerParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") AnswerDO record, @Param("answerParam") AnswerParam answerParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AnswerDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AnswerDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<AnswerDO> records);
}