package com.yingge.qa.dao;

import com.yingge.qa.entity.ProblemSubclassDO;
import com.yingge.qa.entity.ProblemSubclassParam;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
@Mapper
public interface ProblemSubclassDAO {
    /**
     * 根据WHERE条件COUNT
     * @param problemSubclassParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(ProblemSubclassParam problemSubclassParam);

    /**
     * 根据WHERE条件删除
     * @param problemSubclassParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(ProblemSubclassParam problemSubclassParam);

    /**
     * 根据主键删除
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * 插件单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(ProblemSubclassDO record);

    /**
     * 根据字段选择性插件单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(ProblemSubclassDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param problemSubclassParam
     * @return
     *
     * @mbg.generated
     */
    List<ProblemSubclassDO> selectByParam(ProblemSubclassParam problemSubclassParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    ProblemSubclassDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param problemSubclassParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") ProblemSubclassDO record, @Param("problemSubclassParam") ProblemSubclassParam problemSubclassParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param problemSubclassParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") ProblemSubclassDO record, @Param("problemSubclassParam") ProblemSubclassParam problemSubclassParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProblemSubclassDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProblemSubclassDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<ProblemSubclassDO> records);
}