package com.yingge.qa.dao;

import com.yingge.qa.entity.RoleDO;
import com.yingge.qa.entity.RoleParam;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
@Mapper
public interface RoleDAO {
    /**
     * 根据WHERE条件COUNT
     * @param roleParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(RoleParam roleParam);

    /**
     * 根据WHERE条件删除
     * @param roleParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(RoleParam roleParam);

    /**
     * 根据主键删除
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * 插件单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(RoleDO record);

    /**
     * 根据字段选择性插件单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(RoleDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param roleParam
     * @return
     *
     * @mbg.generated
     */
    List<RoleDO> selectByParam(RoleParam roleParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    RoleDO selectByPrimaryKey(Integer id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param roleParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") RoleDO record, @Param("roleParam") RoleParam roleParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param roleParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") RoleDO record, @Param("roleParam") RoleParam roleParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<RoleDO> records);
}