package com.yingge.qa.dao;

import com.yingge.qa.entity.UserDO;
import com.yingge.qa.entity.UserParam;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
@Mapper
public interface UserDAO {
    /**
     * 根据WHERE条件COUNT
     * @param userParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(UserParam userParam);

    /**
     * 根据WHERE条件删除
     * @param userParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(UserParam userParam);

    /**
     * 根据主键删除
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * 插件单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(UserDO record);

    /**
     * 根据字段选择性插件单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(UserDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param userParam
     * @return
     *
     * @mbg.generated
     */
    List<UserDO> selectByParam(UserParam userParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    UserDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param userParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") UserDO record, @Param("userParam") UserParam userParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param userParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") UserDO record, @Param("userParam") UserParam userParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<UserDO> records);
}