package com.yingge.qa.dao;

import com.yingge.qa.entity.UserRoleRefDO;
import com.yingge.qa.entity.UserRoleRefParam;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
@Mapper
public interface UserRoleRefDAO {
    /**
     * 根据WHERE条件COUNT
     * @param userRoleRefParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(UserRoleRefParam userRoleRefParam);

    /**
     * 根据WHERE条件删除
     * @param userRoleRefParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(UserRoleRefParam userRoleRefParam);

    /**
     * 根据主键删除
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * 插件单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(UserRoleRefDO record);

    /**
     * 根据字段选择性插件单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(UserRoleRefDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param userRoleRefParam
     * @return
     *
     * @mbg.generated
     */
    List<UserRoleRefDO> selectByParam(UserRoleRefParam userRoleRefParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    UserRoleRefDO selectByPrimaryKey(Long id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param userRoleRefParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") UserRoleRefDO record, @Param("userRoleRefParam") UserRoleRefParam userRoleRefParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param userRoleRefParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") UserRoleRefDO record, @Param("userRoleRefParam") UserRoleRefParam userRoleRefParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserRoleRefDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRoleRefDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<UserRoleRefDO> records);
}