package com.yingge.qa.service;

import java.util.List;

import com.yingge.qa.entity.AnswerDTO;
import com.yingge.qa.controller.AnswerParameter;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
public interface AnswerService {
    /**
     * 根据参数统计总数
     * @param param
     */
    long count(AnswerParameter param);

    /**
     * 根据参数查询
     * @param param
     */
    AnswerDTO find(AnswerParameter param);

    /**
     * 列表查询
     * @param param
     */
    List<AnswerDTO> list(AnswerParameter param);

    /**
     * 创建
     * @param param
     */
    void create(AnswerParameter param);

    /**
     * 选择性修改
     * @param dto
     * @param param
     */
    void updateSelective(AnswerDTO dto, AnswerParameter param);
}