package com.yingge.qa.service;

import java.util.List;

import com.yingge.qa.controller.ProblemParentParameter;
import com.yingge.qa.entity.ProblemParentDTO;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
public interface ProblemParentService {
    /**
     * 根据参数统计总数
     * @param param
     */
    long count(ProblemParentParameter param);

    /**
     * 根据参数查询
     * @param param
     */
    ProblemParentDTO find(ProblemParentParameter param);

    /**
     * 列表查询
     * @param param
     */
    List<ProblemParentDTO> list(ProblemParentParameter param);

    /**
     * 创建
     * @param param
     */
    void create(ProblemParentParameter param);

    /**
     * 选择性修改
     * @param dto
     * @param param
     */
    void updateSelective(ProblemParentDTO dto, ProblemParentParameter param);
}