package com.yingge.qa.service;

import java.util.List;

import com.yingge.qa.controller.ProblemSubclassParameter;
import com.yingge.qa.entity.ProblemSubclassDTO;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
public interface ProblemSubclassService {
    /**
     * 根据参数统计总数
     * @param param
     */
    long count(ProblemSubclassParameter param);

    /**
     * 根据参数查询
     * @param param
     */
    ProblemSubclassDTO find(ProblemSubclassParameter param);

    /**
     * 列表查询
     * @param param
     */
    List<ProblemSubclassDTO> list(ProblemSubclassParameter param);

    /**
     * 创建
     * @param param
     */
    void create(ProblemSubclassParameter param);

    /**
     * 选择性修改
     * @param dto
     * @param param
     */
    void updateSelective(ProblemSubclassDTO dto, ProblemSubclassParameter param);
}