package com.yingge.qa.service;

import java.util.List;

import com.yingge.qa.controller.UserParameter;
import com.yingge.qa.entity.UserDTO;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
public interface UserService {
    /**
     * 根据参数统计总数
     * @param param
     */
    long count(UserParameter param);

    /**
     * 根据参数查询
     * @param param
     */
    UserDTO find(UserParameter param);

    /**
     * 列表查询
     * @param param
     */
    List<UserDTO> list(UserParameter param);

    /**
     * 创建
     * @param param
     */
    void create(UserParameter param);

    /**
     * 选择性修改
     * @param dto
     * @param param
     */
    void updateSelective(UserDTO dto, UserParameter param);
}