package com.yingge.qa.service;

import java.util.List;

import com.yingge.qa.controller.UserRoleRefParameter;
import com.yingge.qa.entity.UserRoleRefDTO;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
public interface UserRoleRefService {
    /**
     * 根据参数统计总数
     * @param param
     */
    long count(UserRoleRefParameter param);

    /**
     * 根据参数查询
     * @param param
     */
    UserRoleRefDTO find(UserRoleRefParameter param);

    /**
     * 列表查询
     * @param param
     */
    List<UserRoleRefDTO> list(UserRoleRefParameter param);

    /**
     * 创建
     * @param param
     */
    void create(UserRoleRefParameter param);

    /**
     * 选择性修改
     * @param dto
     * @param param
     */
    void updateSelective(UserRoleRefDTO dto, UserRoleRefParameter param);
}