package com.yingge.qa.controller;

import java.io.Serializable;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
public class AnswerParameter implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     */
    private Long id;

    /**
     *   答案内容
     */
    private String answerContent;

    /**
     *   问题编号
     */
    private Long problemId;

    /**
     *   回答者
     */
    private String respondent;

    /**
     *   回答时间
     */
    private String answerTime;

    /**
     *   提问者评论好评次数
     */
    private String count;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAnswerContent() {
        return answerContent;
    }

    public void setAnswerContent(String answerContent) {
        this.answerContent = answerContent;
    }

    public Long getProblemId() {
        return problemId;
    }

    public void setProblemId(Long problemId) {
        this.problemId = problemId;
    }

    public String getRespondent() {
        return respondent;
    }

    public void setRespondent(String respondent) {
        this.respondent = respondent;
    }

    public String getAnswerTime() {
        return answerTime;
    }

    public void setAnswerTime(String answerTime) {
        this.answerTime = answerTime;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }
}