package com.yingge.qa.controller;

import java.util.List;

import com.yingge.qa.entity.AnswerDTO;
import com.yingge.qa.service.AnswerService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
@RestController
@RequestMapping(value = "/Answer")
public class AnswerController {
    @Autowired
    private AnswerService answerService;

    /**
     * 根据参数查找
     */
    @ResponseBody
    @GetMapping("/find")
    public AnswerDTO find(@RequestParam(required = false) Long id, @RequestParam(required = false) String answerContent, @RequestParam(required = false) Long problemId, @RequestParam(required = false) String respondent, @RequestParam(required = false) String answerTime, @RequestParam(required = false) String count) {
        AnswerParameter param = new AnswerParameter();
        param.setId(id);
        param.setAnswerContent(answerContent);
        param.setProblemId(problemId);
        param.setRespondent(respondent);
        param.setAnswerTime(answerTime);
        param.setCount(count);
        return answerService.find(param);
    }

    /**
     * 列表查询
     */
    @ResponseBody
    @GetMapping("/list")
    public List<AnswerDTO> list(@RequestParam(required = false) Long id, @RequestParam(required = false) String answerContent, @RequestParam(required = false) Long problemId, @RequestParam(required = false) String respondent, @RequestParam(required = false) String answerTime, @RequestParam(required = false) String count) {
        AnswerParameter param = new AnswerParameter();
        param.setId(id);
        param.setAnswerContent(answerContent);
        param.setProblemId(problemId);
        param.setRespondent(respondent);
        param.setAnswerTime(answerTime);
        param.setCount(count);
        return answerService.list(param);
    }

    /**
     * 创建
     */
    @RequestMapping("/create")
    public void create(@RequestParam(required = false) Long id, @RequestParam(required = false) String answerContent, @RequestParam(required = false) Long problemId, @RequestParam(required = false) String respondent, @RequestParam(required = false) String answerTime, @RequestParam(required = false) String count) {
        AnswerParameter param = new AnswerParameter();
        param.setId(id);
        param.setAnswerContent(answerContent);
        param.setProblemId(problemId);
        param.setRespondent(respondent);
        param.setAnswerTime(answerTime);
        param.setCount(count);
        answerService.create(param);
    }

    /**
     * 修改
     */
    @RequestMapping("/update")
    public void updateSelective(@RequestParam(required = false) Long id, @RequestParam(required = false) String answerContent, @RequestParam(required = false) Long problemId, @RequestParam(required = false) String respondent, @RequestParam(required = false) String answerTime, @RequestParam(required = false) String count) {
        AnswerDTO dto = new AnswerDTO();
        dto.setId(id);
        dto.setAnswerContent(answerContent);
        dto.setProblemId(problemId);
        dto.setRespondent(respondent);
        dto.setAnswerTime(answerTime);
        dto.setCount(count);
        AnswerParameter param = new AnswerParameter();
        param.setId(id);
        param.setAnswerContent(answerContent);
        param.setProblemId(problemId);
        param.setRespondent(respondent);
        param.setAnswerTime(answerTime);
        param.setCount(count);
        answerService.updateSelective(dto, param);
    }
}