package com.yingge.qa.controller;

import java.io.Serializable;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
public class ProblemSubclassParameter implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     */
    private Long id;

    /**
     *   分类名称
     */
    private String classificationName;

    /**
     *   子类名称
     */
    private String subclassName;

    /**
     *   父类id
     */
    private Long respondent;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getClassificationName() {
        return classificationName;
    }

    public void setClassificationName(String classificationName) {
        this.classificationName = classificationName;
    }

    public String getSubclassName() {
        return subclassName;
    }

    public void setSubclassName(String subclassName) {
        this.subclassName = subclassName;
    }

    public Long getRespondent() {
        return respondent;
    }

    public void setRespondent(Long respondent) {
        this.respondent = respondent;
    }
}