package com.yingge.qa.controller;

import com.yingge.qa.entity.ProblemParentDO;
import com.yingge.qa.entity.ProblemParentDTO;
import org.springframework.beans.BeanUtils;
import org.springframework.stereotype.Service;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
@Service
public class ProblemParentConverter {

    /**
     * DTO模型转换成DO模型
     * @param problemParentDTO
     */
    public ProblemParentDO convertFromDTO(ProblemParentDTO problemParentDTO) {
        ProblemParentDO problemParentDO = new ProblemParentDO();
        BeanUtils.copyProperties(problemParentDTO,problemParentDO);
        return problemParentDO;
    }

    /**
     * DO模型转换成DTO模型
     * @param problemParentDO
     */
    public ProblemParentDTO convertFromDO(ProblemParentDO problemParentDO) {
        ProblemParentDTO problemParentDTO = new ProblemParentDTO();
        BeanUtils.copyProperties(problemParentDO,problemParentDTO);
        return problemParentDTO;
    }
}