package com.yingge.qa.controller;

import java.io.Serializable;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
public class ProblemParentParameter implements Serializable {
    private static final long serialVersionUID = 1L;

    /**
     */
    private Long id;

    /**
     *   问题分类
     */
    private String answerContent;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAnswerContent() {
        return answerContent;
    }

    public void setAnswerContent(String answerContent) {
        this.answerContent = answerContent;
    }
}