package com.yingge.qa.controller;

import java.util.List;

import com.yingge.qa.entity.ProblemSubclassDTO;
import com.yingge.qa.service.ProblemSubclassService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
@RestController
@RequestMapping(value = "/ProblemSubclass")
public class ProblemSubclassController {
    @Autowired
    private ProblemSubclassService problemSubclassService;

    /**
     * 根据参数查找
     */
    @ResponseBody
    @GetMapping("/find")
    public ProblemSubclassDTO find(@RequestParam(required = false) Long id, @RequestParam(required = false) String classificationName, @RequestParam(required = false) String subclassName, @RequestParam(required = false) Long respondent) {
        ProblemSubclassParameter param = new ProblemSubclassParameter();
        param.setId(id);
        param.setClassificationName(classificationName);
        param.setSubclassName(subclassName);
        param.setRespondent(respondent);
        return problemSubclassService.find(param);
    }

    /**
     * 列表查询
     */
    @ResponseBody
    @GetMapping("/list")
    public List<ProblemSubclassDTO> list(@RequestParam(required = false) Long id, @RequestParam(required = false) String classificationName, @RequestParam(required = false) String subclassName, @RequestParam(required = false) Long respondent) {
        ProblemSubclassParameter param = new ProblemSubclassParameter();
        param.setId(id);
        param.setClassificationName(classificationName);
        param.setSubclassName(subclassName);
        param.setRespondent(respondent);
        return problemSubclassService.list(param);
    }

    /**
     * 创建
     */
    @RequestMapping("/create")
    public void create(@RequestParam(required = false) Long id, @RequestParam(required = false) String classificationName, @RequestParam(required = false) String subclassName, @RequestParam(required = false) Long respondent) {
        ProblemSubclassParameter param = new ProblemSubclassParameter();
        param.setId(id);
        param.setClassificationName(classificationName);
        param.setSubclassName(subclassName);
        param.setRespondent(respondent);
        problemSubclassService.create(param);
    }

    /**
     * 修改
     */
    @RequestMapping("/update")
    public void updateSelective(@RequestParam(required = false) Long id, @RequestParam(required = false) String classificationName, @RequestParam(required = false) String subclassName, @RequestParam(required = false) Long respondent) {
        ProblemSubclassDTO dto = new ProblemSubclassDTO();
        dto.setId(id);
        dto.setClassificationName(classificationName);
        dto.setSubclassName(subclassName);
        dto.setRespondent(respondent);
        ProblemSubclassParameter param = new ProblemSubclassParameter();
        param.setId(id);
        param.setClassificationName(classificationName);
        param.setSubclassName(subclassName);
        param.setRespondent(respondent);
        problemSubclassService.updateSelective(dto, param);
    }
}