package com.yingge.qa.controller;

import com.yingge.qa.entity.RoleDO;
import com.yingge.qa.entity.RoleDTO;
import org.springframework.beans.BeanUtils;
import org.springframework.stereotype.Service;

/**
 * This class was generated by Ali-Generator
 * @author zhaoxiongy@163.com
 */
@Service
public class RoleConverter {

    /**
     * DTO模型转换成DO模型
     * @param roleDTO
     */
    public RoleDO convertFromDTO(RoleDTO roleDTO) {
        RoleDO roleDO = new RoleDO();
        BeanUtils.copyProperties(roleDTO,roleDO);
        return roleDO;
    }

    /**
     * DO模型转换成DTO模型
     * @param roleDO
     */
    public RoleDTO convertFromDO(RoleDO roleDO) {
        RoleDTO roleDTO = new RoleDTO();
        BeanUtils.copyProperties(roleDO,roleDTO);
        return roleDTO;
    }
}